import {
  Activity,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BookOpen,
  Calendar,
  CalendarClock,
  Camera,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleHelp,
  CircleSlash,
  Clock,
  Copy,
  Download,
  EllipsisVertical,
  ExternalLink,
  FileText,
  GitBranch,
  GitCommitHorizontal,
  GitPullRequest,
  Globe,
  History,
  Info,
  Languages,
  LayoutDashboard,
  Link2,
  Lock,
  LoaderCircle,
  LogIn,
  LogOut,
  MessageSquare,
  Minus,
  OctagonX,
  Package,
  Pause,
  Pencil,
  Play,
  Plus,
  Radar,
  Radio,
  RefreshCw,
  RotateCcw,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldAlert,
  Smartphone,
  Sparkles,
  Table2,
  Tag,
  Trash2,
  TrendingUp,
  TriangleAlert,
  UserCog,
  UserPlus,
  Users,
  WandSparkles,
  X,
} from 'lucide-react';
/**
 * The frozen glyph vocabulary. The specifications name glyph *meanings* but ship no icon font,
 * sprite or SVG, so Lucide is the substituted set: 24px grid, 1.75 stroke rather than Lucide's
 * default 2, so glyphs sit calmly inside dense evidence tables. This map is the only seam — swap
 * the right-hand side for the project's own set and no consumer changes.
 */
export const GLYPHS = {
  // Signal and state mapping, frozen together with the status vocabulary.
  check: Check,
  'circle-check': CircleCheck,
  'triangle-alert': TriangleAlert,
  'octagon-x': OctagonX,
  'circle-dashed': CircleDashed,
  'circle-help': CircleHelp,
  minus: Minus,
  clock: Clock,
  'loader-circle': LoaderCircle,
  history: History,
  'circle-alert': CircleAlert,
  'circle-slash': CircleSlash,
  pause: Pause,
  archive: Archive,
  'circle-dot': CircleDot,
  'trending-up': TrendingUp,
  'chart-line': ChartLine,
  sparkles: Sparkles,
  languages: Languages,
  // Domain glyphs.
  package: Package,
  'git-branch': GitBranch,
  'git-pull-request': GitPullRequest,
  'git-commit-horizontal': GitCommitHorizontal,
  camera: Camera,
  tag: Tag,
  'file-text': FileText,
  'shield-alert': ShieldAlert,
  'message-square': MessageSquare,
  'book-open': BookOpen,
  globe: Globe,
  users: Users,
  'user-plus': UserPlus,
  radar: Radar,
  scale: Scale,
  bell: Bell,
  'layout-dashboard': LayoutDashboard,
  'table-2': Table2,
  activity: Activity,
  // Interface glyphs.
  info: Info,
  x: X,
  search: Search,
  'search-x': SearchX,
  lock: Lock,
  'link-2': Link2,
  pencil: Pencil,
  plus: Plus,
  'wand-sparkles': WandSparkles,
  send: Send,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'ellipsis-vertical': EllipsisVertical,
  settings: Settings,
  smartphone: Smartphone,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'external-link': ExternalLink,
  'refresh-cw': RefreshCw,
  radio: Radio,
  'log-in': LogIn,
  'log-out': LogOut,
  'user-cog': UserCog,
  play: Play,
  'trash-2': Trash2,
  copy: Copy,
  download: Download,
  'rotate-ccw': RotateCcw,
} as const;

export type IconName = keyof typeof GLYPHS;

/** The frozen vocabulary as data, so a consumer can assert against it. */
export const ICON_NAMES = Object.keys(GLYPHS) as readonly IconName[];
