DROP TRIGGER IF EXISTS alert_occurrences_project_write_guard ON alert_occurrences;
DROP TRIGGER IF EXISTS alert_rules_project_write_guard ON alert_rules;
DROP TRIGGER IF EXISTS radar_overrides_project_write_guard ON radar_overrides;
DROP TRIGGER IF EXISTS radar_selections_project_write_guard ON radar_selections;
DROP TRIGGER IF EXISTS recommendation_evaluations_project_write_guard ON recommendation_evaluations;
DROP TRIGGER IF EXISTS trend_signals_project_write_guard ON trend_signals;
DROP TABLE IF EXISTS alert_transitions;
DROP TABLE IF EXISTS alert_member_state;
DROP TABLE IF EXISTS alert_occurrence_evidence;
DROP TABLE IF EXISTS alert_occurrences;
DROP TABLE IF EXISTS alert_rules;
DROP INDEX IF EXISTS radar_overrides_active_idx;
DROP TABLE IF EXISTS radar_overrides;
DROP TABLE IF EXISTS radar_selections;
DROP TABLE IF EXISTS recommendation_gaps;
DROP TABLE IF EXISTS recommendation_evidence;
DROP TABLE IF EXISTS recommendation_factors;
DROP TABLE IF EXISTS recommendation_evaluations;
DROP INDEX IF EXISTS policy_versions_history_idx;
DROP TABLE IF EXISTS policy_radar_mappings;
DROP TABLE IF EXISTS policy_rules;
ALTER TABLE IF EXISTS policy_families DROP CONSTRAINT IF EXISTS policy_families_active_version_fk;
DROP TABLE IF EXISTS policy_versions;
DROP TABLE IF EXISTS policy_families;
DROP TABLE IF EXISTS trend_signal_evidence;
DROP TABLE IF EXISTS trend_signals;
