// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type AuditEvent struct {
	ID           int64              `json:"id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	ActorID      pgtype.Int8        `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Int8        `json:"resource_id"`
	Details      []byte             `json:"details"`
}

type EvidenceVector struct {
	ID                int64              `json:"id"`
	ObjectReferenceID pgtype.Int8        `json:"object_reference_id"`
	Embedding         pgvector.Vector    `json:"embedding"`
	Model             string             `json:"model"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID         int64              `json:"id"`
	Kind       string             `json:"kind"`
	State      string             `json:"state"`
	Checkpoint []byte             `json:"checkpoint"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ObjectReference struct {
	ID             int64              `json:"id"`
	ObjectKey      string             `json:"object_key"`
	Sha256         []byte             `json:"sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	MediaType      string             `json:"media_type"`
	RetentionState string             `json:"retention_state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	SchemaVersion int32              `json:"schema_version"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type SnowflakeNodeLease struct {
	NodeID         int16              `json:"node_id"`
	HolderID       string             `json:"holder_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
