// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const acquireSnowflakeNode = `-- name: AcquireSnowflakeNode :one
WITH candidate AS (
    SELECT node_id
    FROM generate_series(0, 1023) AS candidates(node_id)
    WHERE NOT EXISTS (
        SELECT 1
        FROM snowflake_node_leases leases
        WHERE leases.node_id = candidates.node_id
          AND leases.lease_expires_at > $3
    )
    ORDER BY node_id
    LIMIT 1
)
INSERT INTO snowflake_node_leases (node_id, holder_id, lease_expires_at, updated_at)
SELECT node_id, $1, $2, $3
FROM candidate
ON CONFLICT (node_id) DO UPDATE
SET holder_id = EXCLUDED.holder_id,
    lease_expires_at = EXCLUDED.lease_expires_at,
    updated_at = EXCLUDED.updated_at
WHERE snowflake_node_leases.lease_expires_at <= EXCLUDED.updated_at
RETURNING node_id, holder_id, lease_expires_at
`

type AcquireSnowflakeNodeParams struct {
	HolderID       string             `json:"holder_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	NowAt          pgtype.Timestamptz `json:"now_at"`
}

type AcquireSnowflakeNodeRow struct {
	NodeID         int16              `json:"node_id"`
	HolderID       string             `json:"holder_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) AcquireSnowflakeNode(ctx context.Context, arg AcquireSnowflakeNodeParams) (AcquireSnowflakeNodeRow, error) {
	row := q.db.QueryRow(ctx, acquireSnowflakeNode, arg.HolderID, arg.LeaseExpiresAt, arg.NowAt)
	var i AcquireSnowflakeNodeRow
	err := row.Scan(&i.NodeID, &i.HolderID, &i.LeaseExpiresAt)
	return i, err
}

const createEvidenceVector = `-- name: CreateEvidenceVector :one
INSERT INTO evidence_vectors (id, object_reference_id, embedding, model)
VALUES ($1, $2, $3, $4)
RETURNING id, object_reference_id, embedding, model, created_at
`

type CreateEvidenceVectorParams struct {
	ID                int64           `json:"id"`
	ObjectReferenceID pgtype.Int8     `json:"object_reference_id"`
	Embedding         pgvector.Vector `json:"embedding"`
	Model             string          `json:"model"`
}

func (q *Queries) CreateEvidenceVector(ctx context.Context, arg CreateEvidenceVectorParams) (EvidenceVector, error) {
	row := q.db.QueryRow(ctx, createEvidenceVector,
		arg.ID,
		arg.ObjectReferenceID,
		arg.Embedding,
		arg.Model,
	)
	var i EvidenceVector
	err := row.Scan(
		&i.ID,
		&i.ObjectReferenceID,
		&i.Embedding,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceVector = `-- name: GetEvidenceVector :one
SELECT id, object_reference_id, embedding, model, created_at
FROM evidence_vectors
WHERE id = $1
`

func (q *Queries) GetEvidenceVector(ctx context.Context, id int64) (EvidenceVector, error) {
	row := q.db.QueryRow(ctx, getEvidenceVector, id)
	var i EvidenceVector
	err := row.Scan(
		&i.ID,
		&i.ObjectReferenceID,
		&i.Embedding,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listObjectReferences = `-- name: ListObjectReferences :many
SELECT id, object_key, sha256, size_bytes, media_type, retention_state, created_at
FROM object_references
WHERE retention_state <> 'purged'
ORDER BY id
`

func (q *Queries) ListObjectReferences(ctx context.Context) ([]ObjectReference, error) {
	rows, err := q.db.Query(ctx, listObjectReferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObjectReference{}
	for rows.Next() {
		var i ObjectReference
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.Sha256,
			&i.SizeBytes,
			&i.MediaType,
			&i.RetentionState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSnowflakeNode = `-- name: RenewSnowflakeNode :one
UPDATE snowflake_node_leases
SET lease_expires_at = $1,
    updated_at = $2
WHERE node_id = $3
  AND holder_id = $4
  AND lease_expires_at > $2
RETURNING node_id, holder_id, lease_expires_at
`

type RenewSnowflakeNodeParams struct {
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	NowAt          pgtype.Timestamptz `json:"now_at"`
	NodeID         int16              `json:"node_id"`
	HolderID       string             `json:"holder_id"`
}

type RenewSnowflakeNodeRow struct {
	NodeID         int16              `json:"node_id"`
	HolderID       string             `json:"holder_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) RenewSnowflakeNode(ctx context.Context, arg RenewSnowflakeNodeParams) (RenewSnowflakeNodeRow, error) {
	row := q.db.QueryRow(ctx, renewSnowflakeNode,
		arg.LeaseExpiresAt,
		arg.NowAt,
		arg.NodeID,
		arg.HolderID,
	)
	var i RenewSnowflakeNodeRow
	err := row.Scan(&i.NodeID, &i.HolderID, &i.LeaseExpiresAt)
	return i, err
}
