// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	AcquireSnowflakeNode(ctx context.Context, arg AcquireSnowflakeNodeParams) (AcquireSnowflakeNodeRow, error)
	CreateEvidenceVector(ctx context.Context, arg CreateEvidenceVectorParams) (EvidenceVector, error)
	GetEvidenceVector(ctx context.Context, id int64) (EvidenceVector, error)
	ListObjectReferences(ctx context.Context) ([]ObjectReference, error)
	RenewSnowflakeNode(ctx context.Context, arg RenewSnowflakeNodeParams) (RenewSnowflakeNodeRow, error)
}

var _ Querier = (*Queries)(nil)
